export const dataSections = {
  heroSection: [
    {
      id: 'heroSectionFirst',
      leftImage: 'https://via.placeholder.com/866x1080',
      title: 'Готові інтер’єрні рішення',
      subTitle: 'для життя та бізнесу',
      midImage: 'https://via.placeholder.com/610x390',
      rightImage: 'https://via.placeholder.com/450x690',
      bottomTitle: 'від 300 $/м²',
      button: 'Докладніше',
    },
    {
      id: 'heroSectionSecond',
      leftImage: 'https://via.placeholder.com/866x1080',
      title: 'Готові інтер’єрні рішення',
      subTitle: 'для життя та эконом',
      midImage: 'https://via.placeholder.com/610x390',
      rightImage: 'https://via.placeholder.com/450x690',
      bottomTitle: 'від 100 $/м²',
      button: 'Докладніше',
    },
    {
      id: 'heroSectionThird',
      leftImage: 'https://via.placeholder.com/866x1080',
      title: 'Готові інтер’єрні рішення',
      subTitle: 'luxury',
      midImage: 'https://via.placeholder.com/610x390',
      rightImage: 'https://via.placeholder.com/450x690',
      bottomTitle: 'від 1000 $/м²',
      button: 'Докладніше',
    },
  ],
  sectionTwo: [
    {
      id: 'sectionTwoFirst',
      subtitle: {
        first: 'Minimalistic',
        second: 'Look',
      },
      firstImage: 'https://via.placeholder.com/490x2000',
      secondImage: 'https://via.placeholder.com/490x2000',
      thirdImage: 'https://via.placeholder.com/490x2000',
      text: 'від 400 $/м²',
      title: 'minimalistic',
    },
    {
      id: 'sectionTwoSecond',
      subtitle: {
        first: 'classic',
        second: 'Look',
      },
      firstImage: 'https://via.placeholder.com/490x2000',
      secondImage: 'https://via.placeholder.com/490x2000',
      thirdImage: 'https://via.placeholder.com/490x2000',
      text: 'від 500 $/м²',
      title: 'classic',
    },
    {
      id: 'sectionTwoThird',
      subtitle: {
        first: 'loft',
        second: 'Look',
      },
      firstImage: 'https://via.placeholder.com/490x2000',
      secondImage: 'https://via.placeholder.com/490x2000',
      thirdImage: 'https://via.placeholder.com/490x2000',
      text: 'від 600 $/м²',
      title: 'loft',
    },
    {
      id: 'sectionTwoFourth',
      subtitle: {
        first: 'scandinavian',
        second: 'Look',
      },
      firstImage: 'https://via.placeholder.com/490x2000',
      secondImage: 'https://via.placeholder.com/490x2000',
      thirdImage: 'https://via.placeholder.com/490x2000',
      text: 'від 700 $/м²',
      title: 'scandinavian',
    },
  ],
  sectionThree: [
    {
      id: 'sectionThreeFirst',
      firstImage: 'https://via.placeholder.com/465x540',
      secondImage: 'https://via.placeholder.com/465x540',
      thirdImage: 'https://via.placeholder.com/960x540',
      fourthImage: 'https://via.placeholder.com/960x540',
      title: 'кухня',
    },
    {
      id: 'sectionThreeSecond',
      firstImage: 'https://via.placeholder.com/465x540',
      secondImage: 'https://via.placeholder.com/465x540',
      thirdImage: 'https://via.placeholder.com/960x540',
      fourthImage: 'https://via.placeholder.com/960x540',
      title: 'вітальня',
    },
    {
      id: 'sectionThreeThird',
      firstImage: 'https://via.placeholder.com/465x540',
      secondImage: 'https://via.placeholder.com/465x540',
      thirdImage: 'https://via.placeholder.com/960x540',
      fourthImage: 'https://via.placeholder.com/960x540',
      title: 'спальня',
    },
    {
      id: 'sectionThreeFourth',
      firstImage: 'https://via.placeholder.com/465x540',
      secondImage: 'https://via.placeholder.com/465x540',
      thirdImage: 'https://via.placeholder.com/960x540',
      fourthImage: 'https://via.placeholder.com/960x540',
      title: 'ванна кімната',
    },
  ],
  sectionFourth: {
    titles: {
      first: {
        title: 'Large',
        subTitle: 'flat',
      },
      second: {
        title: 'Smart',
        subTitle: '',
      },
    },
    images: {
      first: 'https://via.placeholder.com/755x540',
      second: 'https://via.placeholder.com/755x540',
    },
    text: {
      title: 'Капсули  ідеальні для створення смартів',
      // eslint-disable-next-line max-len
      info: 'Капсули  надають широкі можливості для перетворення економічно обтяжливих великих квартир у компактні та прибуткові смарти, цілком готові для життя, продажу чи під здачу в оренду',
      button: 'дивитись смарти',
    },
  },
  sectionSix: [
    {
      id: 'sectionSixFirst',
      firstImage: 'https://via.placeholder.com/600x600',
      secondImage: 'https://via.placeholder.com/600x600',
      thirdImage: 'https://via.placeholder.com/600x480',
      fourthImage: 'https://via.placeholder.com/600x480',
      fiveImage: 'https://via.placeholder.com/600x480',
      nav: 'kit standart',
      title: '1 Збалансований вибір',
      subTitle: 'Для тих, хто цінує якість та надає перевагу  гармонійному поєднанню естетики та функціональності.',
    },
    {
      id: 'sectionSixSecond',
      firstImage: 'https://via.placeholder.com/600x600',
      secondImage: 'https://via.placeholder.com/600x600',
      thirdImage: 'https://via.placeholder.com/600x480',
      fourthImage: 'https://via.placeholder.com/600x480',
      fiveImage: 'https://via.placeholder.com/600x480',
      nav: 'kit select',
      title: '2 Збалансований вибір',
      subTitle: 'Для тих, хто цінує якість та надає перевагу  гармонійному поєднанню естетики та функціональності.',
    },
    {
      id: 'sectionSixThird',
      firstImage: 'https://via.placeholder.com/600x600',
      secondImage: 'https://via.placeholder.com/600x600',
      thirdImage: 'https://via.placeholder.com/600x480',
      fourthImage: 'https://via.placeholder.com/600x480',
      fiveImage: 'https://via.placeholder.com/600x480',
      nav: 'kit green',
      title: '3 Збалансований вибір',
      subTitle: 'Для тих, хто цінує якість та надає перевагу  гармонійному поєднанню естетики та функціональності.',
    },
    {
      id: 'sectionSixFourth',
      firstImage: 'https://via.placeholder.com/600x600',
      secondImage: 'https://via.placeholder.com/600x600',
      thirdImage: 'https://via.placeholder.com/600x480',
      fourthImage: 'https://via.placeholder.com/600x480',
      fiveImage: 'https://via.placeholder.com/600x480',
      nav: 'kit full',
      title: '4 Збалансований вибір',
      subTitle: 'Для тих, хто цінує якість та надає перевагу  гармонійному поєднанню естетики та функціональності.',
    },
  ],
}
